/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * NTOU 拍賣系統 API
 * 海大拍賣系統後端 API 文檔 - 提供註冊、登入、商品管理等功能
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

/**
 * 更新密碼請求
 */
export interface UpdatePasswordRequest {
  /** 目前密碼 */
  currentPassword: string;
  /**
   * 新密碼
   * @minLength 6
   * @maxLength 2147483647
   */
  newPassword: string;
}

/**
 * 更新使用者資訊請求
 */
export interface UpdateUserRequest {
  /**
   * 新的使用者名稱（可選）
   * @minLength 3
   * @maxLength 20
   */
  username?: string;
  /** 電子郵件（可選） */
  email?: string;
  /**
   * 使用者暱稱（可選）
   * @minLength 0
   * @maxLength 50
   */
  nickname?: string;
  /**
   * 聯絡地址（可選）
   * @minLength 0
   * @maxLength 200
   */
  address?: string;
  /**
   * 聯絡電話（可選）
   * @pattern ^[0-9]{10}$
   */
  phoneNumber?: string;
}

/**
 * 使用者資訊回應
 */
export interface UserInfoResponse {
  /** 使用者 ID */
  id?: string;
  /** 使用者名稱 */
  username?: string;
  /** 電子郵件 */
  email?: string;
  /** 使用者暱稱 */
  nickname?: string;
  /** 地址 */
  address?: string;
  /** 電話號碼 */
  phoneNumber?: string;
  /** 平均評分 */
  averageRating?: number;
  /** 評分次數 */
  ratingCount?: number;
}

export type EditProductRequestProductType = typeof EditProductRequestProductType[keyof typeof EditProductRequestProductType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EditProductRequestProductType = {
  DIRECT: 'DIRECT',
  AUCTION: 'AUCTION',
} as const;

export type EditProductRequestProductStatus = typeof EditProductRequestProductStatus[keyof typeof EditProductRequestProductStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EditProductRequestProductStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SOLD: 'SOLD',
  BANNED: 'BANNED',
} as const;

export interface EditProductRequest {
  productName?: string;
  productDescription?: string;
  productImage?: string;
  productType?: EditProductRequestProductType;
  productStock?: number;
  productPrice?: number;
  productCategory?: string;
  productStatus?: EditProductRequestProductStatus;
}

export interface UpdateCartQuantityRequest {
  /** @minimum 0 */
  quantity?: number;
}

export type ProductProductType = typeof ProductProductType[keyof typeof ProductProductType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductProductType = {
  DIRECT: 'DIRECT',
  AUCTION: 'AUCTION',
} as const;

export type ProductProductStatus = typeof ProductProductStatus[keyof typeof ProductProductStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductProductStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SOLD: 'SOLD',
  BANNED: 'BANNED',
} as const;

export interface Product {
  productID?: string;
  sellerID?: string;
  productName?: string;
  productType?: ProductProductType;
  productStatus?: ProductProductStatus;
  productDescription?: string;
  viewCount?: number;
  productCategory?: string;
  averageRating?: number;
  reviewCount?: number;
  updatedTime?: string;
  totalSales?: number;
  createdTime?: string;
  productImage?: string;
  nowHighestBid?: number;
  productStock?: number;
  highestBidderID?: string;
  auctionEndTime?: string;
  productPrice?: number;
}

export interface Cart {
  id?: string;
  userId?: string;
  items?: CartItem[];
}

export interface CartItem {
  itemId?: string;
  productId?: string;
  quantity?: number;
}

export type OrderOrderType = typeof OrderOrderType[keyof typeof OrderOrderType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderOrderType = {
  DIRECT: 'DIRECT',
  AUCTION: 'AUCTION',
} as const;

export type OrderOrderStatus = typeof OrderOrderStatus[keyof typeof OrderOrderStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderOrderStatus = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
} as const;

export interface Order {
  orderID?: string;
  buyerID?: string;
  sellerID?: string;
  cart?: Cart;
  orderTime?: string;
  orderType?: OrderOrderType;
  orderStatus?: OrderOrderStatus;
  orderItems?: OrderItem[];
}

export interface OrderItem {
  productID?: string;
  quantity?: number;
  sellerID?: string;
  price?: number;
  totalPrice?: number;
}

export interface AddToCartRequest {
  productId: string;
  /** @minimum 1 */
  quantity?: number;
}

/**
 * 使用者註冊請求
 */
export interface RegisterRequest {
  /** 使用者名稱 */
  username: string;
  /** 使用者密碼 */
  password: string;
  /** 電子郵件 */
  email: string;
}

/**
 * 認證成功回應
 */
export interface AuthResponse {
  /** JWT Token */
  token?: string;
  /** 使用者名稱 */
  username?: string;
}

/**
 * 使用者登入請求
 */
export interface LoginRequest {
  /** 使用者名稱 */
  username: string;
  /** 使用者密碼 */
  password: string;
}

/**
 * 購物車項目詳細資訊
 */
export interface CartItemDTO {
  /** 購物車項目 ID */
  itemId?: string;
  /** 商品 ID */
  productId?: string;
  /** 商品名稱 */
  productName?: string;
  /** 商品價格 */
  price?: number;
  /** 商品圖片 URL */
  imageUrl?: string;
  /** 賣家 ID */
  sellerId?: string;
  /** 賣家名稱 */
  sellerName?: string;
  /** 數量 */
  quantity?: number;
  /** 小計（價格 × 數量） */
  subtotal?: number;
}

/**
 * 購物車完整回應
 */
export interface CartResponseDTO {
  /** 使用者 ID */
  userId?: string;
  /** 購物車項目列表 */
  items?: CartItemDTO[];
  /** 總金額 */
  totalAmount?: number;
  /** 總項目數 */
  totalItems?: number;
}

export type UpdatePassword401 = { [key: string]: unknown };

export type UpdateUser401 = { [key: string]: unknown };

export type CreateOrder200 = { [key: string]: unknown };

export type CreateAuctionParams = {
/**
 * 起標價格
 */
price: number;
/**
 * 拍賣結束時間 (ISO 8601 格式)
 */
time: string;
};

export type PlaceBidParams = {
/**
 * 出價金額
 */
price: number;
/**
 * 出價者ID
 */
bidderId: string;
};

export type GetAllProductParams = {
/**
 * 頁碼（從1開始）
 */
page?: number;
/**
 * 每頁商品數量
 */
pageSize?: number;
};

export type GetOrderById200 = { [key: string]: unknown };

/**
 * 手動結束指定商品的拍賣，拍賣結束後將無法再出價
 * @summary 結束拍賣
 */
export const terminateAuction = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.put(
      `/api/${id}/terminate`,undefined,options
    );
  }



export const getTerminateAuctionMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof terminateAuction>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof terminateAuction>>, TError,{id: string}, TContext> => {

const mutationKey = ['terminateAuction'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof terminateAuction>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  terminateAuction(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TerminateAuctionMutationResult = NonNullable<Awaited<ReturnType<typeof terminateAuction>>>
    
    export type TerminateAuctionMutationError = AxiosError<unknown>

    /**
 * @summary 結束拍賣
 */
export const useTerminateAuction = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof terminateAuction>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof terminateAuction>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getTerminateAuctionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 更新當前使用者的密碼。需要提供目前密碼進行驗證。
 * @summary 更新使用者密碼
 */
export const updatePassword = (
    updatePasswordRequest: UpdatePasswordRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.put(
      `/api/user/password`,
      updatePasswordRequest,options
    );
  }



export const getUpdatePasswordMutationOptions = <TError = AxiosError<UpdatePassword401>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePassword>>, TError,{data: UpdatePasswordRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updatePassword>>, TError,{data: UpdatePasswordRequest}, TContext> => {

const mutationKey = ['updatePassword'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePassword>>, {data: UpdatePasswordRequest}> = (props) => {
          const {data} = props ?? {};

          return  updatePassword(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof updatePassword>>>
    export type UpdatePasswordMutationBody = UpdatePasswordRequest
    export type UpdatePasswordMutationError = AxiosError<UpdatePassword401>

    /**
 * @summary 更新使用者密碼
 */
export const useUpdatePassword = <TError = AxiosError<UpdatePassword401>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePassword>>, TError,{data: UpdatePasswordRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePassword>>,
        TError,
        {data: UpdatePasswordRequest},
        TContext
      > => {

      const mutationOptions = getUpdatePasswordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 取得當前登入使用者的詳細資訊
 * @summary 取得當前使用者資訊
 */
export const getCurrentUser = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserInfoResponse>> => {
    
    
    return axios.default.get(
      `/api/user/me`,options
    );
  }




export const getGetCurrentUserQueryKey = () => {
    return [
    `/api/user/me`
    ] as const;
    }

    
export const getGetCurrentUserQueryOptions = <TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = AxiosError<UserInfoResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCurrentUserQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUser>>> = ({ signal }) => getCurrentUser({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCurrentUserQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentUser>>>
export type GetCurrentUserQueryError = AxiosError<UserInfoResponse>


export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = AxiosError<UserInfoResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUser>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = AxiosError<UserInfoResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUser>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = AxiosError<UserInfoResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 取得當前使用者資訊
 */

export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = AxiosError<UserInfoResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCurrentUserQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * 更新當前使用者的詳細資訊。所有欄位都是可選的，未提供的欄位保持不變。
 * @summary 更新使用者資訊
 */
export const updateUser = (
    updateUserRequest: UpdateUserRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserInfoResponse>> => {
    
    
    return axios.default.put(
      `/api/user/me`,
      updateUserRequest,options
    );
  }



export const getUpdateUserMutationOptions = <TError = AxiosError<UpdateUser401>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{data: UpdateUserRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{data: UpdateUserRequest}, TContext> => {

const mutationKey = ['updateUser'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUser>>, {data: UpdateUserRequest}> = (props) => {
          const {data} = props ?? {};

          return  updateUser(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserMutationResult = NonNullable<Awaited<ReturnType<typeof updateUser>>>
    export type UpdateUserMutationBody = UpdateUserRequest
    export type UpdateUserMutationError = AxiosError<UpdateUser401>

    /**
 * @summary 更新使用者資訊
 */
export const useUpdateUser = <TError = AxiosError<UpdateUser401>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{data: UpdateUserRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateUser>>,
        TError,
        {data: UpdateUserRequest},
        TContext
      > => {

      const mutationOptions = getUpdateUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 將商品狀態改為 UNAVAILABLE（已下架），商品將不可購買
 * @summary 下架商品
 */
export const withdrawProduct = (
    productID: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.put(
      `/api/products/withdraw/${productID}`,undefined,options
    );
  }



export const getWithdrawProductMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof withdrawProduct>>, TError,{productID: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof withdrawProduct>>, TError,{productID: string}, TContext> => {

const mutationKey = ['withdrawProduct'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof withdrawProduct>>, {productID: string}> = (props) => {
          const {productID} = props ?? {};

          return  withdrawProduct(productID,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type WithdrawProductMutationResult = NonNullable<Awaited<ReturnType<typeof withdrawProduct>>>
    
    export type WithdrawProductMutationError = AxiosError<unknown>

    /**
 * @summary 下架商品
 */
export const useWithdrawProduct = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof withdrawProduct>>, TError,{productID: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof withdrawProduct>>,
        TError,
        {productID: string},
        TContext
      > => {

      const mutationOptions = getWithdrawProductMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 將商品狀態改為 AVAILABLE（已上架），使商品可供購買
 * @summary 上架商品
 */
export const publishProduct = (
    productID: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.put(
      `/api/products/upload/${productID}`,undefined,options
    );
  }



export const getPublishProductMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publishProduct>>, TError,{productID: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof publishProduct>>, TError,{productID: string}, TContext> => {

const mutationKey = ['publishProduct'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof publishProduct>>, {productID: string}> = (props) => {
          const {productID} = props ?? {};

          return  publishProduct(productID,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PublishProductMutationResult = NonNullable<Awaited<ReturnType<typeof publishProduct>>>
    
    export type PublishProductMutationError = AxiosError<unknown>

    /**
 * @summary 上架商品
 */
export const usePublishProduct = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publishProduct>>, TError,{productID: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof publishProduct>>,
        TError,
        {productID: string},
        TContext
      > => {

      const mutationOptions = getPublishProductMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 更新商品的基本資訊（名稱、價格、描述等）
 * @summary 修改商品資訊
 */
export const editProduct = (
    productID: string,
    editProductRequest: EditProductRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.put(
      `/api/products/edit/${productID}`,
      editProductRequest,options
    );
  }



export const getEditProductMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof editProduct>>, TError,{productID: string;data: EditProductRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof editProduct>>, TError,{productID: string;data: EditProductRequest}, TContext> => {

const mutationKey = ['editProduct'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof editProduct>>, {productID: string;data: EditProductRequest}> = (props) => {
          const {productID,data} = props ?? {};

          return  editProduct(productID,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type EditProductMutationResult = NonNullable<Awaited<ReturnType<typeof editProduct>>>
    export type EditProductMutationBody = EditProductRequest
    export type EditProductMutationError = AxiosError<unknown>

    /**
 * @summary 修改商品資訊
 */
export const useEditProduct = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof editProduct>>, TError,{productID: string;data: EditProductRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof editProduct>>,
        TError,
        {productID: string;data: EditProductRequest},
        TContext
      > => {

      const mutationOptions = getEditProductMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 更新購物車中指定項目的數量，數量為 0 時將移除該項目
 * @summary 更新購物車商品數量
 */
export const updateQuantity = (
    itemId: string,
    updateCartQuantityRequest: UpdateCartQuantityRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    
    
    return axios.default.put(
      `/api/cart/items/${itemId}`,
      updateCartQuantityRequest,{
    ...options,}
    );
  }



export const getUpdateQuantityMutationOptions = <TError = AxiosError<string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateQuantity>>, TError,{itemId: string;data: UpdateCartQuantityRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateQuantity>>, TError,{itemId: string;data: UpdateCartQuantityRequest}, TContext> => {

const mutationKey = ['updateQuantity'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateQuantity>>, {itemId: string;data: UpdateCartQuantityRequest}> = (props) => {
          const {itemId,data} = props ?? {};

          return  updateQuantity(itemId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateQuantityMutationResult = NonNullable<Awaited<ReturnType<typeof updateQuantity>>>
    export type UpdateQuantityMutationBody = UpdateCartQuantityRequest
    export type UpdateQuantityMutationError = AxiosError<string>

    /**
 * @summary 更新購物車商品數量
 */
export const useUpdateQuantity = <TError = AxiosError<string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateQuantity>>, TError,{itemId: string;data: UpdateCartQuantityRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateQuantity>>,
        TError,
        {itemId: string;data: UpdateCartQuantityRequest},
        TContext
      > => {

      const mutationOptions = getUpdateQuantityMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 從購物車中移除指定的項目
 * @summary 從購物車移除商品
 */
export const removeFromCart = (
    itemId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    
    
    return axios.default.delete(
      `/api/cart/items/${itemId}`,{
    ...options,}
    );
  }



export const getRemoveFromCartMutationOptions = <TError = AxiosError<string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeFromCart>>, TError,{itemId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof removeFromCart>>, TError,{itemId: string}, TContext> => {

const mutationKey = ['removeFromCart'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeFromCart>>, {itemId: string}> = (props) => {
          const {itemId} = props ?? {};

          return  removeFromCart(itemId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RemoveFromCartMutationResult = NonNullable<Awaited<ReturnType<typeof removeFromCart>>>
    
    export type RemoveFromCartMutationError = AxiosError<string>

    /**
 * @summary 從購物車移除商品
 */
export const useRemoveFromCart = <TError = AxiosError<string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeFromCart>>, TError,{itemId: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeFromCart>>,
        TError,
        {itemId: string},
        TContext
      > => {

      const mutationOptions = getRemoveFromCartMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 建立新商品，商品預設狀態為 PENDING（待上架）
 * @summary 新增商品
 */
export const createProduct = (
    product: Product, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.post(
      `/api/products/add`,
      product,options
    );
  }



export const getCreateProductMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProduct>>, TError,{data: Product}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createProduct>>, TError,{data: Product}, TContext> => {

const mutationKey = ['createProduct'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProduct>>, {data: Product}> = (props) => {
          const {data} = props ?? {};

          return  createProduct(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateProductMutationResult = NonNullable<Awaited<ReturnType<typeof createProduct>>>
    export type CreateProductMutationBody = Product
    export type CreateProductMutationError = AxiosError<unknown>

    /**
 * @summary 新增商品
 */
export const useCreateProduct = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProduct>>, TError,{data: Product}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProduct>>,
        TError,
        {data: Product},
        TContext
      > => {

      const mutationOptions = getCreateProductMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const createOrder = (
    order: Order, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CreateOrder200>> => {
    
    
    return axios.default.post(
      `/api/orders/add`,
      order,options
    );
  }



export const getCreateOrderMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOrder>>, TError,{data: Order}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createOrder>>, TError,{data: Order}, TContext> => {

const mutationKey = ['createOrder'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createOrder>>, {data: Order}> = (props) => {
          const {data} = props ?? {};

          return  createOrder(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateOrderMutationResult = NonNullable<Awaited<ReturnType<typeof createOrder>>>
    export type CreateOrderMutationBody = Order
    export type CreateOrderMutationError = AxiosError<unknown>

    export const useCreateOrder = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOrder>>, TError,{data: Order}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createOrder>>,
        TError,
        {data: Order},
        TContext
      > => {

      const mutationOptions = getCreateOrderMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 將商品設定為拍賣模式，需指定起標價和結束時間。時間格式為 ISO 8601 (yyyy-MM-ddTHH:mm:ss)
 * @summary 建立拍賣商品
 */
export const createAuction = (
    id: string,
    params: CreateAuctionParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.post(
      `/api/createAucs/${id}`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getCreateAuctionMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAuction>>, TError,{id: string;params: CreateAuctionParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createAuction>>, TError,{id: string;params: CreateAuctionParams}, TContext> => {

const mutationKey = ['createAuction'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createAuction>>, {id: string;params: CreateAuctionParams}> = (props) => {
          const {id,params} = props ?? {};

          return  createAuction(id,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateAuctionMutationResult = NonNullable<Awaited<ReturnType<typeof createAuction>>>
    
    export type CreateAuctionMutationError = AxiosError<unknown>

    /**
 * @summary 建立拍賣商品
 */
export const useCreateAuction = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAuction>>, TError,{id: string;params: CreateAuctionParams}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createAuction>>,
        TError,
        {id: string;params: CreateAuctionParams},
        TContext
      > => {

      const mutationOptions = getCreateAuctionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 將指定商品以指定數量加入購物車，若已存在則累加數量
 * @summary 加入商品到購物車
 */
export const addToCart = (
    addToCartRequest: AddToCartRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    
    
    return axios.default.post(
      `/api/cart/items`,
      addToCartRequest,{
    ...options,}
    );
  }



export const getAddToCartMutationOptions = <TError = AxiosError<string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addToCart>>, TError,{data: AddToCartRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof addToCart>>, TError,{data: AddToCartRequest}, TContext> => {

const mutationKey = ['addToCart'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addToCart>>, {data: AddToCartRequest}> = (props) => {
          const {data} = props ?? {};

          return  addToCart(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddToCartMutationResult = NonNullable<Awaited<ReturnType<typeof addToCart>>>
    export type AddToCartMutationBody = AddToCartRequest
    export type AddToCartMutationError = AxiosError<string>

    /**
 * @summary 加入商品到購物車
 */
export const useAddToCart = <TError = AxiosError<string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addToCart>>, TError,{data: AddToCartRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addToCart>>,
        TError,
        {data: AddToCartRequest},
        TContext
      > => {

      const mutationOptions = getAddToCartMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 對指定商品進行出價，出價金額必須高於當前最高出價
 * @summary 競標出價
 */
export const placeBid = (
    id: string,
    params: PlaceBidParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.post(
      `/api/bids/${id}`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getPlaceBidMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof placeBid>>, TError,{id: string;params: PlaceBidParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof placeBid>>, TError,{id: string;params: PlaceBidParams}, TContext> => {

const mutationKey = ['placeBid'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof placeBid>>, {id: string;params: PlaceBidParams}> = (props) => {
          const {id,params} = props ?? {};

          return  placeBid(id,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PlaceBidMutationResult = NonNullable<Awaited<ReturnType<typeof placeBid>>>
    
    export type PlaceBidMutationError = AxiosError<unknown>

    /**
 * @summary 競標出價
 */
export const usePlaceBid = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof placeBid>>, TError,{id: string;params: PlaceBidParams}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof placeBid>>,
        TError,
        {id: string;params: PlaceBidParams},
        TContext
      > => {

      const mutationOptions = getPlaceBidMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 新使用者註冊帳號。註冊成功後會自動登入並返回 JWT Token。
 * @summary 使用者註冊
 */
export const register = (
    registerRequest: RegisterRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AuthResponse>> => {
    
    
    return axios.default.post(
      `/api/auth/register`,
      registerRequest,options
    );
  }



export const getRegisterMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterRequest}, TContext> => {

const mutationKey = ['register'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof register>>, {data: RegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  register(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterMutationResult = NonNullable<Awaited<ReturnType<typeof register>>>
    export type RegisterMutationBody = RegisterRequest
    export type RegisterMutationError = AxiosError<unknown>

    /**
 * @summary 使用者註冊
 */
export const useRegister = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof register>>,
        TError,
        {data: RegisterRequest},
        TContext
      > => {

      const mutationOptions = getRegisterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 使用者登入系統。登入成功後返回 JWT Token，前端需要在後續請求的 Authorization Header 中攜帶此 Token。
 * @summary 使用者登入
 */
export const login = (
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AuthResponse>> => {
    
    
    return axios.default.post(
      `/api/auth/login`,
      loginRequest,options
    );
  }



export const getLoginMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  login(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = LoginRequest
    export type LoginMutationError = AxiosError<unknown>

    /**
 * @summary 使用者登入
 */
export const useLogin = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {

      const mutationOptions = getLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 分頁查詢所有商品，支援自訂每頁商品數量
 * @summary 取得商品列表（分頁）
 */
export const getAllProduct = (
    params?: GetAllProductParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Product>> => {
    
    
    return axios.default.get(
      `/api/products`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetAllProductQueryKey = (params?: GetAllProductParams,) => {
    return [
    `/api/products`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllProductQueryOptions = <TData = Awaited<ReturnType<typeof getAllProduct>>, TError = AxiosError<unknown>>(params?: GetAllProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProduct>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllProductQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllProduct>>> = ({ signal }) => getAllProduct(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllProduct>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllProductQueryResult = NonNullable<Awaited<ReturnType<typeof getAllProduct>>>
export type GetAllProductQueryError = AxiosError<unknown>


export function useGetAllProduct<TData = Awaited<ReturnType<typeof getAllProduct>>, TError = AxiosError<unknown>>(
 params: undefined |  GetAllProductParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProduct>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllProduct>>,
          TError,
          Awaited<ReturnType<typeof getAllProduct>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllProduct<TData = Awaited<ReturnType<typeof getAllProduct>>, TError = AxiosError<unknown>>(
 params?: GetAllProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProduct>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllProduct>>,
          TError,
          Awaited<ReturnType<typeof getAllProduct>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllProduct<TData = Awaited<ReturnType<typeof getAllProduct>>, TError = AxiosError<unknown>>(
 params?: GetAllProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProduct>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 取得商品列表（分頁）
 */

export function useGetAllProduct<TData = Awaited<ReturnType<typeof getAllProduct>>, TError = AxiosError<unknown>>(
 params?: GetAllProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProduct>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllProductQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * 根據商品 ID 查詢商品詳細資訊
 * @summary 取得單一商品資訊
 */
export const getProductById = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Product>> => {
    
    
    return axios.default.get(
      `/api/products/${id}`,options
    );
  }




export const getGetProductByIdQueryKey = (id?: string,) => {
    return [
    `/api/products/${id}`
    ] as const;
    }

    
export const getGetProductByIdQueryOptions = <TData = Awaited<ReturnType<typeof getProductById>>, TError = AxiosError<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProductByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProductById>>> = ({ signal }) => getProductById(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProductByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getProductById>>>
export type GetProductByIdQueryError = AxiosError<unknown>


export function useGetProductById<TData = Awaited<ReturnType<typeof getProductById>>, TError = AxiosError<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductById>>,
          TError,
          Awaited<ReturnType<typeof getProductById>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductById<TData = Awaited<ReturnType<typeof getProductById>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProductById>>,
          TError,
          Awaited<ReturnType<typeof getProductById>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProductById<TData = Awaited<ReturnType<typeof getProductById>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 取得單一商品資訊
 */

export function useGetProductById<TData = Awaited<ReturnType<typeof getProductById>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProductByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const getOrderById = (
    orderID: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetOrderById200>> => {
    
    
    return axios.default.get(
      `/api/orders/${orderID}`,options
    );
  }




export const getGetOrderByIdQueryKey = (orderID?: string,) => {
    return [
    `/api/orders/${orderID}`
    ] as const;
    }

    
export const getGetOrderByIdQueryOptions = <TData = Awaited<ReturnType<typeof getOrderById>>, TError = AxiosError<unknown>>(orderID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrderById>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrderByIdQueryKey(orderID);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrderById>>> = ({ signal }) => getOrderById(orderID, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(orderID), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrderById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOrderByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getOrderById>>>
export type GetOrderByIdQueryError = AxiosError<unknown>


export function useGetOrderById<TData = Awaited<ReturnType<typeof getOrderById>>, TError = AxiosError<unknown>>(
 orderID: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrderById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrderById>>,
          TError,
          Awaited<ReturnType<typeof getOrderById>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrderById<TData = Awaited<ReturnType<typeof getOrderById>>, TError = AxiosError<unknown>>(
 orderID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrderById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrderById>>,
          TError,
          Awaited<ReturnType<typeof getOrderById>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrderById<TData = Awaited<ReturnType<typeof getOrderById>>, TError = AxiosError<unknown>>(
 orderID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrderById>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetOrderById<TData = Awaited<ReturnType<typeof getOrderById>>, TError = AxiosError<unknown>>(
 orderID: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrderById>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOrderByIdQueryOptions(orderID,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * 取得當前登入使用者的購物車，包含商品完整資訊（名稱、價格、圖片、賣家等）
 * @summary 取得購物車
 */
export const getCart = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CartResponseDTO>> => {
    
    
    return axios.default.get(
      `/api/cart`,options
    );
  }




export const getGetCartQueryKey = () => {
    return [
    `/api/cart`
    ] as const;
    }

    
export const getGetCartQueryOptions = <TData = Awaited<ReturnType<typeof getCart>>, TError = AxiosError<CartResponseDTO>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCart>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCartQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCart>>> = ({ signal }) => getCart({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCart>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCartQueryResult = NonNullable<Awaited<ReturnType<typeof getCart>>>
export type GetCartQueryError = AxiosError<CartResponseDTO>


export function useGetCart<TData = Awaited<ReturnType<typeof getCart>>, TError = AxiosError<CartResponseDTO>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCart>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCart>>,
          TError,
          Awaited<ReturnType<typeof getCart>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCart<TData = Awaited<ReturnType<typeof getCart>>, TError = AxiosError<CartResponseDTO>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCart>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCart>>,
          TError,
          Awaited<ReturnType<typeof getCart>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCart<TData = Awaited<ReturnType<typeof getCart>>, TError = AxiosError<CartResponseDTO>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCart>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 取得購物車
 */

export function useGetCart<TData = Awaited<ReturnType<typeof getCart>>, TError = AxiosError<CartResponseDTO>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCart>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCartQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * 清空當前使用者的購物車，移除所有商品
 * @summary 清空購物車
 */
export const clearCart = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/cart`,options
    );
  }



export const getClearCartMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clearCart>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof clearCart>>, TError,void, TContext> => {

const mutationKey = ['clearCart'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof clearCart>>, void> = () => {
          

          return  clearCart(axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ClearCartMutationResult = NonNullable<Awaited<ReturnType<typeof clearCart>>>
    
    export type ClearCartMutationError = AxiosError<void>

    /**
 * @summary 清空購物車
 */
export const useClearCart = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clearCart>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof clearCart>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getClearCartMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 查詢所有正在進行拍賣的商品列表
 * @summary 取得所有拍賣中的商品
 */
export const getAllAuctionProduct = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.get(
      `/api/auctions/`,options
    );
  }




export const getGetAllAuctionProductQueryKey = () => {
    return [
    `/api/auctions/`
    ] as const;
    }

    
export const getGetAllAuctionProductQueryOptions = <TData = Awaited<ReturnType<typeof getAllAuctionProduct>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllAuctionProduct>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllAuctionProductQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllAuctionProduct>>> = ({ signal }) => getAllAuctionProduct({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllAuctionProduct>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllAuctionProductQueryResult = NonNullable<Awaited<ReturnType<typeof getAllAuctionProduct>>>
export type GetAllAuctionProductQueryError = AxiosError<unknown>


export function useGetAllAuctionProduct<TData = Awaited<ReturnType<typeof getAllAuctionProduct>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllAuctionProduct>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllAuctionProduct>>,
          TError,
          Awaited<ReturnType<typeof getAllAuctionProduct>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllAuctionProduct<TData = Awaited<ReturnType<typeof getAllAuctionProduct>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllAuctionProduct>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllAuctionProduct>>,
          TError,
          Awaited<ReturnType<typeof getAllAuctionProduct>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllAuctionProduct<TData = Awaited<ReturnType<typeof getAllAuctionProduct>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllAuctionProduct>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 取得所有拍賣中的商品
 */

export function useGetAllAuctionProduct<TData = Awaited<ReturnType<typeof getAllAuctionProduct>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllAuctionProduct>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllAuctionProductQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * 永久刪除商品資料
 * @summary 刪除商品
 */
export const deleteProduct = (
    productID: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.delete(
      `/api/products/delete/${productID}`,options
    );
  }



export const getDeleteProductMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProduct>>, TError,{productID: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteProduct>>, TError,{productID: string}, TContext> => {

const mutationKey = ['deleteProduct'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProduct>>, {productID: string}> = (props) => {
          const {productID} = props ?? {};

          return  deleteProduct(productID,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteProductMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProduct>>>
    
    export type DeleteProductMutationError = AxiosError<unknown>

    /**
 * @summary 刪除商品
 */
export const useDeleteProduct = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProduct>>, TError,{productID: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProduct>>,
        TError,
        {productID: string},
        TContext
      > => {

      const mutationOptions = getDeleteProductMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
